# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e961f020d75fb8a35d20a5187a98b2a4f5ebfd4e3ed53ea4a79e492697b533e90bf308c95366281a47fde0a93357bef43a43b6a86aca5830ce1420f10023ea5e

test:
  secret_key_base: 8f22e5902b36b6d9153998b6fc9d30348c065a2b55ad1fe4f27c7fdedea69edcac5ee70f721f5fb76746b696d5f96812b66108b7bdbb83d26ba4c5b1ca918a94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
